apiVersion: v1
kind: Service
metadata:
  name: url-shortener-app
spec:
  selector:
    app: url-shortener-app
  ports:
    - protocol: TCP
      port: 8000      # Port exposed internally
      targetPort: 8000 # Port your app listens to
      nodePort: 30001  # NodePort (accessible externally)
  type: NodePort
